server:
  port: 8088
spring:
  application:
    name: gazerbase
  # PostgreSQL ?????
  datasource:
    url: jdbc:postgresql://localhost:15432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  # JPA ??
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
